//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BellMagazine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acts
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int TypeOfMalfuctionID { get; set; }
        public int PhoneID { get; set; }
    
        public virtual Phones Phones { get; set; }
        public virtual TypeOfCrash TypeOfCrash { get; set; }
    }
}
