//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BellMagazine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public int PhoneID { get; set; }
        public int ClientID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> isRefund { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Phones Phones { get; set; }
    }
}
